[package]
name = "spimquest"
version = "0.1.0"
authors = ["Declan Hopkins <hopkins.declan@gmail.com>"]

[dependencies]
time = "0.1.38"
pathfinding = "0.1.13"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["image", "gfx"]
